# -*- coding: utf-8 -*-
"""Main_MinorProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pUKfpEF1HzMnuoYK6sM3nVCOfDDvI6RK
"""

!pip install transformers torch

from transformers import pipeline

emotion_classifier = pipeline("text-classification",
                              model="j-hartmann/emotion-english-distilroberta-base")

texts = [
    "I feel very anxious before exams.",
    "I am so happy with my results!",
    "I’m really angry about the assignment deadline.",
    "I feel sad because I failed the test.",
    "I’m scared I won’t perform well in the presentation."
]

for t in texts:
    print(t, "->", emotion_classifier(t))

from flask import Flask, request, jsonify

# Create Flask app
app = Flask(__name__)

@app.route("/predict", methods=["POST"])
def predict():
    data = request.get_json()
    text = data.get("text", "")
    if not text:
        return jsonify({"error": "No text provided"}), 400

    preds = emotion_classifier(text)
    return jsonify(preds)

!pip install flask-ngrok

!pip install pyngrok

from pyngrok import ngrok

!ngrok config add-authtoken "32abuFajIqJ7hLW0fviRC47uE7r_4HToV3L9bX3qv9vSd8GQ1"

public_url = ngrok.connect(5000)
print("Public URL:", public_url)

app.run(port=5000)